name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: Docker/setup-buildx-action@v1

    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and run Docker containers
      run: |
        docker-compose -f docker-compose.yml up -d --build

    - name: Wait for services
      run: |
        sleep 30
        docker-compose -f docker-compose.yml ps

    - name: Run tests
      run: |
        # здесь могли быть ваши тесты))
        echo "допустим тесты прошли успешно)"
      
    - name: Stop and remove containers
      run: docker-compose -f docker-compose.yml down
