name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: Docker/setup-buildx-action@v1

    - name: Build and run Docker containers
      run: |
        docker-compose -f docker-compose.yml up -d --build

    - name: Wait for services
      run: |
        sleep 30
        docker-compose -f docker-compose.yml ps

    - name: Run tests
      run: |
        # здесь могли быть ваши тесты))
        echo "допустим тесты прошли успешно)"
      
